name: Publish to Docker Hub registry
on:
  workflow_dispatch:

jobs:

  build-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_URI: "registry.hub.docker.com"
      DOCKER_USERNAME: "yanaturiak"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: "registry.hub.docker.com"
          username: "yanaturiak"
          password: ${{ secrets.DOCKER_HUB_API_KEY }}

      - name: Build and push Backend Docker image
        run: |-
          BACKEND_IMAGE="${DOCKER_REPO_URI}/${DOCKER_USERNAME}/shelfshark-backend"
          docker build -t ${BACKEND_IMAGE}:latest -t ${BACKEND_IMAGE}:${GITHUB_SHA::8} backend/
          docker push -a ${BACKEND_IMAGE}